### ISSUE TITLE
Add removeCombined flag to allow opting out of removing files during build

### ISSUE THREAD

**Issue by chrylis** [dbashford/mimosa-require#45]
After optimization, `mimosa-require` removes JavaScript files with modules that were rolled up. This appears to be part of the module itself and not r.js; the log lines are colorized, and I have `removeCombined: false` in my overrides. (Setting `removeCombined: true` causes r.js to remove them, and the debug message do not appear.)

I'm running Karma in a downstream build step (`mimosa-karma` isn't working for me), and I need to keep the module files for testing.

Since r.js has its own `removeCombined` option, I suggest not running the cleanup phase when the external r.js is used.

**Comment by dbashford** [comment]
I can't rely on r.js.  If there are multiple single page apps (not modules) then r.js is invoked multiple times.  If using r.js' removeCombined, then after the first run all the files would be nuked.  And if those files are needed for the 2nd run...

**Comment by dbashford** [comment]
So, considering mimosa cannot use r.js, is the request here to be able to configure mimosa's removeCombine?

**Comment by chrylis** [comment]
I believe so. Is this already an option? I dumped the config and didn't notice anything that looked applicable.

**Comment by dbashford** [comment]
Nope, would need to add that.

Sent from myMail for iOS

**Comment by dbashford** [comment]
`v3.1.5` and `v2.3.5` contain a new flag.  See [the docs](https://github.com/dbashford/mimosa-require#requireoptimizeremovecombined-boolean).
